In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn import datasets

iris_data = datasets.load_iris()
iris_df = pd.DataFrame(iris_data["data"], columns=iris_data["feature_names"])
iris_df["class"] = iris_data.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
X = iris_df.iloc[:, :-1].values
y = iris_df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
from sklearn.naive_bayes import GaussianNB

gnb_model = GaussianNB()

In [8]:
gnb_model.fit(X_train, y_train)

GaussianNB()

In [10]:
gnb_model.predict_proba(X_test)

array([[4.15880005e-088, 9.95527834e-001, 4.47216606e-003],
       [1.00000000e+000, 1.31031235e-013, 2.21772205e-020],
       [9.83170191e-285, 2.70138564e-012, 1.00000000e+000],
       [9.54745274e-092, 9.74861431e-001, 2.51385686e-002],
       [1.08679560e-103, 8.31910700e-001, 1.68089300e-001],
       [1.00000000e+000, 6.77693844e-013, 7.14891338e-021],
       [2.79985841e-051, 9.99963925e-001, 3.60749274e-005],
       [3.47130487e-172, 4.26099520e-007, 9.99999574e-001],
       [8.87424368e-094, 9.93578115e-001, 6.42188515e-003],
       [1.01525828e-057, 9.99952885e-001, 4.71152410e-005],
       [3.89708229e-148, 2.58773323e-004, 9.99741227e-001],
       [1.00000000e+000, 1.41103765e-016, 9.36331484e-025],
       [1.00000000e+000, 2.50761563e-016, 5.99383407e-024],
       [1.00000000e+000, 3.02382725e-016, 3.69654979e-024],
       [1.00000000e+000, 2.31820777e-016, 1.18856457e-023],
       [6.09343428e-105, 4.23901472e-001, 5.76098528e-001],
       [8.42661111e-199, 2.69249362e-007

In [11]:
y_predict = gnb_model.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [13]:
confusion_matrix(y_test, y_predict)

array([[19,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 13]])

In [15]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [16]:
y_predict_train = gnb_model.predict(X_train)
confusion_matrix(y_train, y_predict_train)

array([[31,  0,  0],
       [ 0, 34,  3],
       [ 0,  3, 34]])

In [ ]:
# TODO: 16 Dey 1401

class MyGuassianNB:
    def fit:
        pass
    def predict_prob:
        pass
    def predict:
        pass