In [1]:
import numpy as np

## Basic


1 ----> 0_dim \n



N_dim -----> (N-1)_dim

In [30]:
my_arr = np.array([[[1, 2]], [[2, 5]], [[3, 8]]], dtype=np.int32)

In [31]:
my_arr.ndim

3

In [33]:
my_arr.shape

(3, 1, 2)

In [34]:
my_arr.dtype

dtype('int32')

In [35]:
my_arr.itemsize

4

In [36]:
my_arr.size

6

## Slicing, Selection

In [49]:
my_arr = np.array([[[1, 2, 3], [5, 8, 32]], [[2, 5, 12], [76, 12, 18]], [[3, 3, 8], [54, 22, -21]]], dtype=np.int32)

In [50]:
my_arr[0, 0, 1]

2

In [51]:
my_arr[1][1][0]

76

In [39]:
my_arr[0, 0, 1] = 12

In [56]:
my_arr[:, 1 , :2]

array([[ 5,  8],
       [76, 12],
       [54, 22]], dtype=int32)

## generate ndarray

In [63]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [66]:
np.ones((3, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [71]:
kashi_arr = np.ones((11, 11))
kashi_arr[2:-2, 2:-2] = 0
kashi_arr[5, 5] = 11

kashi_arr

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [127]:
kashi_mehrdad = np.zeros((11, 11))
kashi_mehrdad[[0, 1, -2, -1]] = 1
kashi_mehrdad[:, [0, 1, -2, -1]] = 1
kashi_mehrdad[5, 5] = 11
kashi_mehrdad

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [84]:
kashi_mehrdad[[3, 8,10]]

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
kashi_mehrdad[2:6, 3:9]

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 11.,  0.,  0.,  0.]])

In [89]:
kashi_mehrdad[ [0, 1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10]] = 11

In [90]:
kashi_mehrdad

array([[ 1.,  1.,  1.,  1.,  1., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  1.,  1.,  1., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  0.,  0.,  0., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  0.,  0.,  0., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  0.,  0.,  0., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  0.,  0.,  0., 11., 11., 11., 11., 11., 11.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [94]:
def get_ghotr_asli(arr: np.ndarray):
    result = []
    if(arr.ndim != 2 and arr.shape[0] == arr.shape[1]):
        raise ValueError("matrix morabaei bede!!")
    for i in range(arr.shape[0]):
        result.append(arr[i, i])
        
    return np.array(result)

In [96]:
kashi_mehrdad[2: 7, 2: 7]

array([[ 0.,  0.,  0., 11., 11.],
       [ 0.,  0.,  0., 11., 11.],
       [ 0.,  0.,  0., 11., 11.],
       [ 0.,  0.,  0., 11., 11.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [95]:
get_ghotr_asli(kashi_mehrdad[2: 7, 2: 7])

array([ 0.,  0.,  0., 11.,  0.])

In [ ]:
# for i in kashi_mehrdad:
#     for j in i:
#         print(j)
for index, val in np.ndenumerate(kashi_mehrdad):
    print(index, "---> ", val)

## masking

In [128]:
test_size = (kashi_mehrdad <= 3)

In [129]:
kashi_mehrdad[test_size] = 0

In [130]:
kashi_mehrdad

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## Broadcasting

In [134]:
kashi_mehrdad = kashi_mehrdad + 2

In [135]:
kashi_mehrdad / 2

array([[1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 6.5, 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ]])

In [136]:
kashi_mehrdad ** 2

array([[  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4., 169.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.]])

In [ ]:
np.ones((12, 10, 5)) + np.ones((1, 10, 1))

## Math

In [ ]:
np.sin(kashi_mehrdad)

In [ ]:
np.exp(kashi_mehrdad)

## Random

In [163]:
np.random.randint(2, 12, (12, 3))

array([[10,  4,  5],
       [ 5, 10, 11],
       [ 5, 10,  5],
       [ 3,  2,  6],
       [ 4,  9,  8],
       [ 5,  9,  7],
       [ 9,  5,  5],
       [ 5,  3, 10],
       [ 7,  6,  4],
       [ 2,  9,  6],
       [ 5,  6,  2],
       [11,  6,  8]])

In [166]:
np.random.normal(size=(12, 2, 2))

array([[[-1.42107078,  0.28671742],
        [-0.08195556,  1.2526694 ]],

       [[-0.19308902, -0.41534449],
        [ 0.59060222,  1.3222937 ]],

       [[-0.22272063, -0.52068149],
        [ 0.95759902, -0.37118836]],

       [[ 0.52913061,  0.12016303],
        [-0.44290724, -0.64234959]],

       [[-1.14988895,  0.34806544],
        [-0.09964226,  0.25958464]],

       [[-1.63543034, -0.12306215],
        [ 0.48101021, -0.0461254 ]],

       [[-0.01224676,  0.55927288],
        [ 0.50113451,  0.39658475]],

       [[ 1.65491289, -0.51574364],
        [ 0.35119992, -0.20194434]],

       [[-1.26096731, -0.03094959],
        [ 1.16623087,  0.33306377]],

       [[-1.335882  ,  0.47080435],
        [-1.78481272, -1.71644693]],

       [[-1.1851614 ,  0.44360859],
        [ 2.12136   ,  1.16099154]],

       [[ 0.28993122,  0.11861903],
        [-0.30471598, -0.29399657]]])

In [167]:
def guassian(miu, variance, shape=(1,)) -> np.ndarray:
    result = np.sqrt(variance) * np.random.normal(size = shape) + miu
    return result

In [177]:
g_dis = guassian(2, 4, (40, 50))
g_dis

array([[ 1.44318726, -0.23972046, -1.24832513, ...,  3.22301215,
         2.32447144,  6.35969167],
       [ 2.22453154,  2.73261774,  1.81117186, ...,  0.41080285,
         2.32965423,  1.70195356],
       [-0.6718083 ,  0.35308472,  4.15341459, ...,  2.70907605,
         1.31961232,  1.06431831],
       ...,
       [-0.96181257,  3.65539781, -1.42663726, ...,  2.21534206,
         1.21007819,  0.43851476],
       [ 4.06646221,  3.42629541,  1.19476676, ...,  2.31417136,
         1.40788431,  2.93044768],
       [ 3.80244704,  1.64227255,  1.22311942, ..., -2.27269939,
         1.6058361 , -0.63278537]])

In [178]:
np.mean(g_dis)

1.9774195780810673

In [179]:
np.var(g_dis)

3.9695941937512336

In [180]:
np.min(g_dis)

-4.880327829996737

In [181]:
np.max(g_dis)

8.610176329721014

In [189]:
np.argmax(g_dis)

640

In [191]:
np.unravel_index(np.argmax(g_dis), g_dis.shape)

(12, 40)

In [192]:
g_dis[12, 40]

8.610176329721014

## Axis

In [203]:
test_axis = np.random.randint(2, 10, (4, 3, 2))
test_axis

array([[[4, 2],
        [5, 4],
        [6, 4]],

       [[6, 6],
        [6, 8],
        [6, 4]],

       [[9, 6],
        [9, 4],
        [3, 3]],

       [[3, 9],
        [9, 3],
        [8, 8]]])

In [207]:
np.max(test_axis, axis=1)

array([[6, 4],
       [6, 8],
       [9, 6],
       [9, 9]])

## reshape

In [214]:
test_reshape = np.random.randint(1, 10, (12, ))
test_reshape

array([4, 8, 9, 9, 2, 7, 7, 7, 4, 4, 7, 5])

In [222]:
test_reshape.reshape(1, 2, -1)

array([[[4, 8, 9, 9, 2, 7],
        [7, 7, 4, 4, 7, 5]]])

## concatenate, vstack, hstack

In [252]:
a = np.random.randint(1, 10, (2, 3))
a

array([[5, 4, 6],
       [3, 6, 2]])

In [253]:
b = np.random.randint(1, 10, (2, 3))
b

array([[8, 4, 5],
       [1, 4, 3]])

In [254]:
np.concatenate((a, b), axis=0)

array([[5, 4, 6],
       [3, 6, 2],
       [8, 4, 5],
       [1, 4, 3]])

In [255]:
np.concatenate((a, b), axis=1)

array([[5, 4, 6, 8, 4, 5],
       [3, 6, 2, 1, 4, 3]])

In [256]:
np.hstack((a, b))

array([[5, 4, 6, 8, 4, 5],
       [3, 6, 2, 1, 4, 3]])

In [258]:
np.vstack((a, b))

array([[5, 4, 6],
       [3, 6, 2],
       [8, 4, 5],
       [1, 4, 3]])

In [263]:
np.append(a, b)

array([[5, 4, 6, 3, 6, 2],
       [8, 4, 5, 1, 4, 3]])

In [264]:
np.insert(a, 1, 10)

array([ 5, 10,  4,  6,  3,  6,  2])

In [271]:
c = a.copy()

In [272]:
a[1, 2]  = 15

In [287]:
c[1, 1] = -5
c

array([[-2,  6, 12],
       [-2, -5, 20]])

In [288]:
c.sort(axis=0)
c

array([[-2, -5, 12],
       [-2,  6, 20]])

## Algebra

In [289]:
np.linalg

<module 'numpy.linalg' from '/home/ashkan/Documents/ML3/venv/lib/python3.8/site-packages/numpy/linalg/__init__.py'>